name: Deploy

on:
  push:
    branches: [ 'development', 'master' ]
  pull_request:
    branches: [ 'development', 'master' ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '11.15.0'
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          git remote set-url origin "https://${{ github.token }}@github.com/energywebfoundation/ew-did-registry.git" > /dev/null 2>&1
          git reset --hard
          git fetch origin master:master
          git fetch origin development:development

      - name: Set npm credentials
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc

      - name: Install package
        run: |
          npm install
          npm run setup

      - name: Build package
        run: npm run build

      - name: Test
        run: npm run test-rpc

      - name: Deploy on development branch
        if: github.ref == 'refs/heads/development'
        run: |
          git checkout development
          npm run publish:canary

      - name: Deploy on master branch
        if: github.ref == 'refs/heads/master'
        run: |
          git checkout master
          npm run publish:release
          git checkout development
          git merge origin/master
          git push origin development
